"""empty message

Revision ID: 8a3133b3a8ea
Revises: cc7a319e7284
Create Date: 2023-12-07 19:30:59.409028

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8a3133b3a8ea'
down_revision = 'cc7a319e7284'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=60), nullable=False),
    sa.Column('users_name', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('users_birth', sa.Date(), nullable=True),
    sa.Column('users_phone', sa.String(length=45), nullable=True),
    sa.Column('address_main', sa.String(length=255), nullable=True),
    sa.Column('address_sub', sa.String(length=255), nullable=True),
    sa.Column('createdate', sa.DateTime(), nullable=True),
    sa.Column('updatedate', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('users_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Ciga',
    sa.Column('ciga_id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('video_url', sa.String(length=255), nullable=True),
    sa.Column('capture_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['Users.users_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ciga_id')
    )
    op.create_table('Phone',
    sa.Column('phone_id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('video_url', sa.String(length=255), nullable=True),
    sa.Column('capture_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['Users.users_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('phone_id')
    )
    op.create_table('Sleep',
    sa.Column('sleep_id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('video_url', sa.String(length=255), nullable=True),
    sa.Column('capture_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['Users.users_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sleep_id')
    )
    op.drop_table('phone')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('email')

    op.drop_table('users')
    op.drop_table('ciga')
    op.drop_table('sleep')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sleep',
    sa.Column('sleep_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('users_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=False),
    sa.Column('video_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('capture_url', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['users.users_id'], name='sleep_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sleep_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ciga',
    sa.Column('ciga_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('users_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=False),
    sa.Column('video_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('capture_url', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['users.users_id'], name='ciga_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ciga_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('users_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nickname', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('users_name', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('users_birth', sa.DATE(), nullable=True),
    sa.Column('users_phone', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('address_main', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('address_sub', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('createdate', mysql.DATETIME(), nullable=True),
    sa.Column('updatedate', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('users_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=False)

    op.create_table('phone',
    sa.Column('phone_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('users_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=False),
    sa.Column('video_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('capture_url', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['users.users_id'], name='phone_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('phone_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('Sleep')
    op.drop_table('Phone')
    op.drop_table('Ciga')
    op.drop_table('Users')
    # ### end Alembic commands ###
