"""empty message

Revision ID: cc7a319e7284
Revises: 
Create Date: 2023-12-07 17:30:22.350749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc7a319e7284'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=60), nullable=False),
    sa.Column('users_name', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('users_birth', sa.Date(), nullable=True),
    sa.Column('users_phone', sa.String(length=45), nullable=True),
    sa.Column('address_main', sa.String(length=255), nullable=True),
    sa.Column('address_sub', sa.String(length=255), nullable=True),
    sa.Column('createdate', sa.DateTime(), nullable=True),
    sa.Column('updatedate', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('users_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Ciga',
    sa.Column('ciga_id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('video_url', sa.String(length=255), nullable=True),
    sa.Column('capture_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['Users.users_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ciga_id')
    )
    op.create_table('Phone',
    sa.Column('phone_id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('video_url', sa.String(length=255), nullable=True),
    sa.Column('capture_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['Users.users_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('phone_id')
    )
    op.create_table('Sleep',
    sa.Column('sleep_id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('video_url', sa.String(length=255), nullable=True),
    sa.Column('capture_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['Users.users_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sleep_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Sleep')
    op.drop_table('Phone')
    op.drop_table('Ciga')
    op.drop_table('Users')
    # ### end Alembic commands ###
